Weapons
Tursh/CaveCrawler pull request #4
Opened 2021-01-02 07:58 UTC by musique88

Played around in many files... sorry.

2021-01-02 21:32 UTC, Tursh requested changes
There are some weird indentation, the shoot function need some modification and the constructor can have less paramters than that

2021-01-02 21:32 UTC, Tursh commented on include/World/Player.h
> +		void Shoot(World *world, CC::Weapon &selectedWeapon);
What's going on with the indentations here, lol?

2021-01-02 21:32 UTC, Tursh commented on include/Inventory/Weapon.h
> +		std::shared_ptr<Entities::Projectile> getSharedProjectile() const;
In Projectiles.h add "typedef std::shared_ptr<Entities::Projectile> SharedProjectile;" so now you can put "SharedProjectile" as the return type.

2021-01-02 21:32 UTC, Tursh commented on include/Inventory/Weapon.h
> +		std::array<int, NUMBER_OF_ELEMENTS> requirements() const;
Return a const reference of the array so you don't have to clone the array each time.

2021-01-02 21:32 UTC, Tursh commented on include/Inventory/Weapon.h
> +				bool automatic = false);
Hmmm... That's a lot of parameters. You could reduce them by giving in the constructor a projectile that contains its speed, size and duration. And btw, the float values are not consistent :p.

2021-01-02 21:32 UTC, Tursh commented on include/Inventory/Inventory.h
> +		std::array<std::optional<Weapon>, 5> &getToolbar();
Return it as a const ref, you don't want anyone to modify the toolbar without passing thought the inventory.

2021-01-02 21:32 UTC, Tursh commented on include/Inventory/Inventory.h
> +		Weapon& getWeapon();
Same thing here

2021-01-02 21:32 UTC, Tursh commented on include/World/Player.h
> +		void init();
I'm starting to question if it's github that is showing those weird indentation.

2021-01-02 21:32 UTC, Tursh commented on src/Inventory/Inventory.cpp
> +		selectedWeapon_= 0;
Use a initializer list to define toolbar_ and selectedWeapon_

2021-01-02 21:32 UTC, Tursh commented on include/Inventory/Inventory.h
> +		void setWeapon(Weapon weapon, int index);
You could get the weapon as a const ref if you don't intend to modify it.

2021-01-02 21:32 UTC, Tursh commented on src/Inventory/Inventory.cpp
> +				weapon.value().update();
weapon->update();? I don't know std::optional so not sure.

2021-01-02 21:32 UTC, Tursh commented on src/Inventory/Projectile.cpp
> +		setSpeed(velocity);
Why you set speed after setting the velocity? SetSpeed => as_ = speed, so just put as_(velocity) in you initializer list.

2021-01-02 21:32 UTC, Tursh commented on include/Inventory/Projectile.h
> +		void setPositions(glm::vec3 position = glm::vec3(0),
Put all the parameters as const ref.

2021-01-02 21:32 UTC, Tursh commented on src/World/Player.cpp
> +    	init();
init?

2021-01-02 21:32 UTC, Tursh commented on src/World/Player.cpp
> +	}
You should do those calculations in the weapon function.

2021-01-02 23:53 UTC, musique88 commented on include/Inventory/Inventory.h
> +		Weapon& getWeapon();
I need to be able to modify the selected weapon for fire rate related calculations

2021-01-03 03:04 UTC, Tursh requested changes
Good stuff, but needs some changes

2021-01-03 03:04 UTC, Tursh commented on include/Inventory/Inventory.h
> +		Weapon& getWeapon();
Then do those calculation inside the inventory or the weapon class or don't return it as a ref.

2021-01-03 03:04 UTC, Tursh commented on src/World/Player.cpp
> +	void Player::Shoot(World *world, CC::Weapon &selectedWeapon)
World could be removed as a parameter here

2021-01-03 03:04 UTC, Tursh commented on src/World/World.cpp
> +				//TODO Dont know how to destroy shared pointers correctly
We just need a removeEntity in world, but that's a TODO too lol

2021-01-03 03:04 UTC, Tursh commented on src/World/World.cpp
> +        Physics::BoxCollider entityHitbox = entity->getHitbox();
Refactor is tough job

2021-01-06 05:49 UTC, Tursh requested changes
Just a little mistake on your weapon call condition

2021-01-06 05:49 UTC, Tursh commented on src/World/Player.cpp
>  			if (selectedWeapon.cost_ >= inventory[selectedWeapon.elemental_] && selectedWeapon.canShoot())
<=

2021-01-06 05:53 UTC, merged